[uwsgi]
wsgi-file = /usr/local/searxng/searxng/webapp.py
module = searxng.webapp
http = 0.0.0.0:8080
chdir = /usr/local/searxng/searxng/
master = true
processes = 4
threads = 4
thunder-lock = true
buffer-size = 65536
offload-threads = 4
reload-on-rss = 500
printf = "SearXNG ready at http://0.0.0.0:8080"
